[tool.poetry]
name = "quinn"
version = "0.1.0"
description = "Pyspark helper methods to maximize developer efficiency"
authors = ["MrPowers <matthewkevinpowers@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
cytoolz = "0.9.0.1"
pytest = "3.9.2"
pytest-cov = "2.6.0"
pyspark = "2.4.0"

[tool.poetry.dev-dependencies]
pytest = "3.9.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
